name: data_viz_workshop
channels:
    - conda-forge
dependencies: 
    - python=3.9
    - bokeh=2.4.2
    - ffmpeg=4.3.1
    - geopandas=0.10.2
    - jupyterlab=3.3.0
    - matplotlib=3.5.1
    - numpy=1.22.3
    - pandas=1.4.1
    - seaborn=0.11.2
    - shapely=1.8.0
    - pyviz::geoviews-core=1.9.5
    - pyviz::geoviews=1.9.5
    - pyviz::holoviews=1.14.8
    - pyviz::hvplot=0.7.3
    - pyviz::panel=0.12.7
