name: Local Test with act

on:
  workflow_dispatch:

jobs:
  test:
    container:
      image: catthehacker/ubuntu:act-latest
    
    env:
      OPENAI_API_KEY: "123"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest