version: '3.8'

volumes:
  data:

services:
  redisdb:
    image: redis:latest
    volumes:
      - data:/data
    ports:
      - 6379:6379

  streamlit:
    image: streamlit/sl:1
    build:
      context: .
    ports:
      - "8501:8501"
    entrypoint: streamlit run app.py