name: format

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter: [ruff] #, mypy]
        include:
          - linter: ruff
            command: ruff check --fix . --exclude ./notebook/
          # - linter: mypy
          #   command: mypy . --exclude ./notebook/
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync --frozen
      - name: Run ${{ matrix.linter }} check
        run: uv run ${{ matrix.command }}
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: format-logs
          path: ./logs