name: "online_auth_class"

services:
  auth-api-service:
    image: "auth-api-img"
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    ports:
      - "9900:9900"
    volumes:
      - ./auth_service:/code
