# Travis CI configuration file
# http://about.travis-ci.org/docs/
dist: trusty

language: python

# Available Python versions:
# http://about.travis-ci.org/docs/user/ci-environment/#Python-VM-images
python:
  - "3.5"
  - "3.6"

# Dependencies installation commands
install:
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install -r requirements-ci.txt

before_script:
 - "flake8 --config=config/flake8rc *.py"
 - "pylint --rcfile=config/pylintrc *.py"

script:
  - "python -m unittest discover"

notifications:
  email: false

sudo: false
branches:
  only:
    - master
git:
  depth: 300
