version: '3'

services:
  minio1:
    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage1:/data
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    restart: always
  minio2:
    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
    ports:
      - "9020:9000"
      - "9021:9001"
    volumes:
      - ./minio_storage2:/data
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    restart: always
  minio3:
    image: minio/minio:RELEASE.2023-06-29T05-12-28Z
    ports:
      - "9030:9000"
      - "9031:9001"
    volumes:
      - ./minio_storage3:/data
    command: server --console-address ":9001" /data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    restart: always
