version: '3'
services:
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "./404.html:/usr/share/nginx/html/404.html"
      - "./50x.html:/usr/share/nginx/html/50x.html"
    ports:
      - 9999:9999
