# docker-compose.yml

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatdb
    ports:
      - "7433:5432"
    volumes:
      - ./db/database_setup.sql:/docker-entrypoint-initdb.d/database_setup.sql

  streamlit:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - postgres
    env_file:
      - .env      

  #vector database with persistent storage
  vecdb:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vecdb
    ports:
      - 6433:5432      
    volumes:
      - ./vecdb:/var/lib/postgresql/database
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 3s
      retries: 10

  # langfuse for LLM Analytics
  langfuse:
     image: langfuse/langfuse:2
     environment:
       DATABASE_URL: postgresql://postgres:postgres@vecdb:5432/langfuse
       NEXTAUTH_URL: http://localhost:3000
       NEXTAUTH_SECRET: mysecret
       SALT: mysalt
       ENCRYPTION_KEY: "0000000000000000000000000000000000000000000000000000000000000000"
       TELEMETRY_ENABLED: false
       LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES: false
       LANGFUSE_INIT_ORG_ID: chat2db-organization
       LANGFUSE_INIT_ORG_NAME: Chat2db Organization
       LANGFUSE_INIT_PROJECT_ID: chat2db-project
       LANGFUSE_INIT_PROJECT_NAME: Chat2db Project
       LANGFUSE_INIT_PROJECT_PUBLIC_KEY: pk-lf-6dca9fac-db43-4d97-8043-f7b0e5c2d7f7
       LANGFUSE_INIT_PROJECT_SECRET_KEY: sk-lf-7826e99b-3f42-4589-8cea-21b1e3c3c868
       LANGFUSE_INIT_USER_EMAIL: demo@example.com
       LANGFUSE_INIT_USER_NAME: Demo
       LANGFUSE_INIT_USER_PASSWORD: demo-only
     ports:
       - "3000:3000"
     depends_on:
       vecdb:
         condition: service_healthy