version: "3.7"

services:
  streamlit-wealth-and-health:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    networks:
      - stnet

networks:
  stnet: