version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_DB: studentdb
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student
    volumes:
      - postgres_volume:/var/lib/postgresql/data/

volumes:
  postgres_volume:
