version: '3'
services:
  nginx:
    image: wyveo/nginx-php-fpm:php82
    volumes:
      - ./nginx:/etc/nginx/
      - ./htpasswd:/htpasswd
      - ./html:/usr/share/nginx/html
    ports:
      - 80:80
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
    volumes:
      - ./my-datavolume:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
