import Image from "next/image";
import Link from "next/link";
import "../styles/globals.css";
// https://jordanthirkle.hashnode.dev/learned-how-to-create-a-global-header-and-footer-with-layouttsx-in-nextjs-13-app-router
export const metadata = {
  title: "AJ's Blog",
  description: 'Generated by AJ',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const header = (
    <header>
      <div className="text-center bg-slate-800 p-8 my-6 rounded-md">
        <Image
          src="/images/Althusser.png"
          width={40}
          height={40}
          className="mx-auto"
          alt={"logo"}
        />
        <Link href="/">
          <h1 className="text-2xl text-white font-bold mt-4">AJ's Blog</h1>
        </Link>
        <p className="text-slate-300"> Welcome to my blerg.</p>
      </div>
    </header>
  );

  const footer = (
    <footer>
      <div className="border-t border-slate-400 mt-12 py-6 text-center text-slate-400">
        <h3>Designed by AJ</h3>
      </div>
    </footer>
  );


  return (
    <html>
      <head />
      <body>
        <div className="mx-auto  max-w-2xl px-6">
          {header}
            {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
