language: python

python:
  - "3.6"
  - "3.7"
  - "3.8"

dist: xenial

services:
  - redis-server

install:
  - pip install tox-travis

script:
  - tox

notifications:
  email:
    on_success: never
    on_failure: never