model: 'llama3' 
embedding_model : 'llama3'
collection_name: "rag-chroma"
GOOGLE_CSE_ID: ""
GOOGLE_API_KEY: ""
ollama_url: "http://localhost:11434"
#Used for evaluation
OPENAI_API_KEY: ""
OPENAI_ORGANIZATION: ""