langugage: python
python:
    - "3.8"

services:
    - docker

before_script: 
    - pip install docker-compose

script:
    - bash ./run_tests.sh

after_success:
    - coveralls

branches:
  only: 
    - master