---

dataset:
  name: "medalpaca/medical_meadow_medical_flashcards"

model:
  name: "mistralai/Mistral-7B-v0.1"
  quantization: 4 # 8 or 4 if you want to do quantization with BitsAndBytes
  gradient_checkpointing: True # ! Ensure it matches that in train.train_arguments
  use_fast_tokenizer: False
  lora:
    peft_lora_r: 16
    peft_lora_alpha: 64
    target_modules: ["q_proj","v_proj"]

train:
  save_every_round: 5
  seq_length: 512
  padding_side: "left"
  training_arguments:
    learning_rate: 5e-5
    per_device_train_batch_size: 16
    gradient_accumulation_steps: 1
    logging_steps: 10
    max_steps: 2000
    report_to: null
    save_steps: 200
    save_total_limit: 10
    gradient_checkpointing: True # ! Ensure it matches that in model
    lr_scheduler_type: "cosine"
