version: '3'
services:
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./front:/var/www/front
      - ./files:/var/www/files
    ports:
      - 9999:9999
