# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python image
FROM python:3.10-slim

# Set environment variables for email and optional API key
ENV PUBMED_EMAIL=your-email@example.com
# ENV PUBMED_API_KEY=your-api-key  # Uncomment and set if you have an API key

# Set the working directory
WORKDIR /app

# Copy project files
COPY . .

# Install dependencies
RUN pip install --no-cache-dir .

# Define entrypoint
ENTRYPOINT ["python", "-m", "mcp_simple_pubmed"]
