[theme]
base="light"

# Primary accent for interactive elements
primaryColor = '#1194A2'

# Background color for the main content area
backgroundColor = '#ffffff'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#cbd5e1'

# Color used for almost all text
textColor = '#334155'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

[server]

# The port where the server will listen for browser connections.
# Default: 8501
port = 8501

[browser]

# Disables sending usage statistics to Streamlit.
gatherUsageStats = false
